<?xml version="1.0"?>
<package format="2">
  <name>exomy</name>
  <version>3.0.0</version>
  <description>The ExoMy ROS package</description>

  <maintainer email="email@email.com">0xD0M1M0</maintainer>
  <license>GPLv3</license>
  <url type="website">https://github.com/esa-prl/ExoMy</url>
  <author email="email@email.com">0xD0M1M0</author>

  <buildtool_depend>ament_cmake_ros</buildtool_depend>
  <build_depend>rclpy</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_export_depend>rclpy</build_export_depend>
  <build_export_depend>std_msgs</build_export_depend>
  <build_export_depend>sensor_msgs</build_export_depend>
  <exec_depend>python-rpi.gpio</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>

  <build_depend>message_generation</build_depend>
  <exec_depend>message_runtime</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
